# Generated by Django 5.1.3 on 2024-11-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_crpc"),
    ]

    operations = [
        migrations.CreateModel(
            name="MVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.TextField()),
                ("section_title", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
